// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/delivery/delivery.proto

package delivery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpMethod int32

const (
	HttpMethod_HTTP_METHOD_UNSPECIFIED HttpMethod = 0
	HttpMethod_GET                     HttpMethod = 1
	HttpMethod_POST                    HttpMethod = 2
	HttpMethod_PUT                     HttpMethod = 3
	HttpMethod_DELETE                  HttpMethod = 4
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "DELETE",
	}
	HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"GET":                     1,
		"POST":                    2,
		"PUT":                     3,
		"DELETE":                  4,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_delivery_delivery_proto_enumTypes[0].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_proto_delivery_delivery_proto_enumTypes[0]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

type QueueMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        HttpMethod             `protobuf:"varint,2,opt,name=method,proto3,enum=delivery.v1.HttpMethod" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessageRequest) Reset() {
	*x = QueueMessageRequest{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessageRequest) ProtoMessage() {}

func (x *QueueMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessageRequest.ProtoReflect.Descriptor instead.
func (*QueueMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMessageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *QueueMessageRequest) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_HTTP_METHOD_UNSPECIFIED
}

func (x *QueueMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueueMessageRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type QueueMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMessageResponse) Reset() {
	*x = QueueMessageResponse{}
	mi := &file_proto_delivery_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMessageResponse) ProtoMessage() {}

func (x *QueueMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMessageResponse.ProtoReflect.Descriptor instead.
func (*QueueMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *QueueMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *QueueMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_delivery_delivery_proto protoreflect.FileDescriptor

const file_proto_delivery_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/delivery/delivery.proto\x12\vdelivery.v1\"\x89\x01\n" +
	"\x13QueueMessageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12/\n" +
	"\x06method\x18\x02 \x01(\x0e2\x17.delivery.v1.HttpMethodR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\"M\n" +
	"\x14QueueMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*Q\n" +
	"\n" +
	"HttpMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x042f\n" +
	"\x0fDeliveryService\x12S\n" +
	"\fQueueMessage\x12 .delivery.v1.QueueMessageRequest\x1a!.delivery.v1.QueueMessageResponseB6Z4github.com/bilalabdelkadir/chis/internal/pb/deliveryb\x06proto3"

var (
	file_proto_delivery_delivery_proto_rawDescOnce sync.Once
	file_proto_delivery_delivery_proto_rawDescData []byte
)

func file_proto_delivery_delivery_proto_rawDescGZIP() []byte {
	file_proto_delivery_delivery_proto_rawDescOnce.Do(func() {
		file_proto_delivery_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_delivery_delivery_proto_rawDesc), len(file_proto_delivery_delivery_proto_rawDesc)))
	})
	return file_proto_delivery_delivery_proto_rawDescData
}

var file_proto_delivery_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_delivery_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_delivery_delivery_proto_goTypes = []any{
	(HttpMethod)(0),              // 0: delivery.v1.HttpMethod
	(*QueueMessageRequest)(nil),  // 1: delivery.v1.QueueMessageRequest
	(*QueueMessageResponse)(nil), // 2: delivery.v1.QueueMessageResponse
}
var file_proto_delivery_delivery_proto_depIdxs = []int32{
	0, // 0: delivery.v1.QueueMessageRequest.method:type_name -> delivery.v1.HttpMethod
	1, // 1: delivery.v1.DeliveryService.QueueMessage:input_type -> delivery.v1.QueueMessageRequest
	2, // 2: delivery.v1.DeliveryService.QueueMessage:output_type -> delivery.v1.QueueMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_delivery_delivery_proto_init() }
func file_proto_delivery_delivery_proto_init() {
	if File_proto_delivery_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_delivery_delivery_proto_rawDesc), len(file_proto_delivery_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_delivery_delivery_proto_goTypes,
		DependencyIndexes: file_proto_delivery_delivery_proto_depIdxs,
		EnumInfos:         file_proto_delivery_delivery_proto_enumTypes,
		MessageInfos:      file_proto_delivery_delivery_proto_msgTypes,
	}.Build()
	File_proto_delivery_delivery_proto = out.File
	file_proto_delivery_delivery_proto_goTypes = nil
	file_proto_delivery_delivery_proto_depIdxs = nil
}
